### ISSUE TITLE
Occasional clip-clopping during fast travel on horseback

### ISSUE THREAD

**Issue by TheNewBob** [TheNewBob/TediousTravel#9]
Has started somewhen in a November build of DFU. Not yet sure if I can do anything about that.

**Comment by petchema** [comment]
I think one can be closed now?
https://github.com/Interkarma/daggerfall-unity/pull/1068

**Comment by TheNewBob** [comment]
Indeed it can. I might need somebody to maintain the maintainer of this mod... :)
